### ISSUE TITLE
wisteria --checkup when no config file : boom !

### ISSUE THREAD

**Issue by suizokukan** [suizokukan/wisteria#45]
$ wisteria --checkup when no config file : boom !

Traceback (most recent call last):
  File "/home/kobayashi/.local/bin/wisteria", line 5, in <module>
    from wisteria.wisteria import main
  File "/home/kobayashi/.local/lib/python3.8/site-packages/wisteria/wisteria.py", line 1002, in <module>
    checkup()
  File "/home/kobayashi/.local/lib/python3.8/site-packages/wisteria/wisteria.py", line 880, in checkup
    if not wisteria.data.check(config):
UnboundLocalError: local variable 'config' referenced before assignment

**Comment by suizokukan** [comment]
Fixed: see task-378 (in branch 0.2.4).
