### ISSUE TITLE
poetry run bin/wisteria --cmp="pickle(ini)"  : boom

### ISSUE THREAD

**Issue by suizokukan** [suizokukan/wisteria#49]
poetry run bin/wisteria --cmp="pickle(ini)" (without --filter):

$ poetry run bin/wisteria --cmp="pickle(ini)"
> cwc data object 'wisteria.cwc.pgnreader.cwc_iaswn.chessgames' must be skipped. This is normally not a problem: it just means that a module has not be installed. By example, if the Iaswn serializer has 
not been installed you can't use the 'wisteria.cwc.pgnreader.cwc_iaswn.chessgames' data object.
> cwc data object 'wisteria.cwc.simple.cwc_iaswn.simpleclass' must be skipped. This is normally not a problem: it just means that a module has not be installed. By example, if the Iaswn serializer has 
not been installed you can't use the 'wisteria.cwc.pgnreader.cwc_iaswn.chessgames' data object.
/home/kobayashi/wisteria/wisteria/matplotgraphs.py:218: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig, axes = pyplot.subplots()
Traceback (most recent call last):
  File "bin/wisteria", line 50, in <module>
    sys.exit(main())
  File "/home/kobayashi/wisteria/wisteria/wisteria.py", line 1396, in main
    compute_results__res = compute_results()
  File "/home/kobayashi/wisteria/wisteria/results.py", line 374, in compute_results
    return average_results(raw_results)
  File "/home/kobayashi/wisteria/wisteria/results.py", line 120, in average_results
    decoding_time += raw_serialization_result.decoding_time
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'NoneType'

**Comment by suizokukan** [comment]
Fixed: see task-384 (in 0.2.4)
